easy_admin:
    entities:
        Users:
            class: App\Entity\User
            disabled_actions: ['new', 'delete']
            list:
                fields: ['id', 'email']
            form:
                fields:
                    - {property: 'email'}
